[package]
name = "clienten"
version = "0.1.0"
edition = "2021"

[build]
rustflags = ["-Clink-arg=-fuse-ld=lld"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.1"
config = "0.13.3"
# heim = "0.0.11"
sysinfo = "0.28.4"


# stuff you need:
# nix-shell -p pkgs.darwin.IOKit
# wtf.
