[package]
name = "standard_styled"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.0"
tokio = { version = "1.27.0", features = [ "io-util", "io-std", "macros", "process", "rt-multi-thread", "time" ] }
